name = "ChainaCobbleverse"
author = "SomitadePony"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88aa388f404ce6e5a5be767e596bd45d9cd1db102b68c0a67dcf314e7dc3d66d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
