name = "ChainaCobbleverse"
author = "SomitadePony"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfe12abd116de5de49d96b122610a2ec6dfc2a1635b07dc00a1f8fb83dcabf4d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "world/datapacks"
