name = "ChainaCobbleverse"
author = "SomitadePony"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fd6c0867a28792cdf2447de4106523ff6b9cb849d6a1a4f862de4a87574b4ff"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "world/datapacks"
