#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 23 14:21:30 PET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=COBBLEVERSE - Shaders
