#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Sat Aug 15 22:24:09 PET 2026
alwaysLogTamperWarnings=true
